name: nlp_tutor
description: "nlp tutor application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  youtube_player_iframe: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/chapters.json

